"""Hand-built seed knowledge trees for the Phase-0 pilot.

Design principles (from the design discussion):
- The **root is not a category** ("Reactions"). We do not claim to know the
  single ultimate principle governing all of chemistry, so the true root is
  *open/unknown* — modeled as ``kind="open_root"`` and rendered faintly. The
  real top level is a **forest of fundamental governing principles**.
- Internal nodes are **principles and mechanisms**, not reaction-class names.
  E.g. cross-coupling is not a principle; the principle is the *organometallic
  catalytic cycle*, and the mechanism is *oxidative addition / transmetalation
  / reductive elimination*. A named reaction (Suzuki, ...) is a leaf.
- A node flagged ``"host": True`` is a **leaf-hosting branch** (the deepest
  mechanistic level). New paper entities attach under a host, or are flagged
  as exceptions when nothing fits.

Each node: ``{"name", "kind", "desc", "host"?, "children": [...]}``.
``desc`` is the text we embed to match candidate leaves against the branch.
"""

from __future__ import annotations

# ── by_reaction_type: principle -> mechanism -> leaf(reaction) ───────────────
REACTION_TREE = {
    "name": "(unifying principle unknown)",
    "kind": "open_root",
    "desc": "The single principle unifying all chemical reactivity is not "
            "claimed; the top level is a forest of fundamental governing "
            "principles.",
    "children": [
        {
            "name": "Polar (heterolytic) bond reorganization",
            "kind": "principle",
            "desc": "Reactivity governed by paired-electron flow between an "
                    "electron-rich nucleophile and an electron-poor electrophile; "
                    "controlled by charge, electronegativity, polarization and "
                    "acid-base (HSAB) matching.",
            "children": [
                {
                    "name": "Nucleophilic substitution",
                    "kind": "mechanism", "host": True,
                    "desc": "Substitution at a saturated or aromatic center where a "
                            "nucleophile displaces a leaving group via an SN1/SN2 "
                            "(or addition-elimination) pathway.",
                    "children": [],
                },
                {
                    "name": "Nucleophilic addition & condensation",
                    "kind": "mechanism", "host": True,
                    "desc": "Addition of a nucleophile to a carbonyl or other polar "
                            "pi-electrophile, including aldol, Michael and "
                            "condensation reactions with loss of a small molecule.",
                    "children": [],
                },
                {
                    "name": "beta-elimination",
                    "kind": "mechanism", "host": True,
                    "desc": "Loss of two substituents from adjacent atoms to form a "
                            "pi-bond via an E1/E2 pathway.",
                    "children": [],
                },
            ],
        },
        {
            "name": "Single-electron transfer & radical chemistry",
            "kind": "principle",
            "desc": "Reactivity proceeding through homolytic bond changes and "
                    "open-shell radical intermediates generated by single-electron "
                    "transfer, photoexcitation or homolysis.",
            "children": [
                {
                    "name": "Photoredox single-electron transfer",
                    "kind": "mechanism", "host": True,
                    "desc": "Visible-light photocatalysis that transfers a single "
                            "electron to or from a substrate to generate radical "
                            "ions that then form new bonds, including "
                            "metallaphotoredox cycles.",
                    "children": [],
                },
                {
                    "name": "Hydrogen-atom transfer",
                    "kind": "mechanism", "host": True,
                    "desc": "Abstraction of a hydrogen atom to generate a carbon (or "
                            "heteroatom) radical that is subsequently functionalized; "
                            "the basis of many C-H activation reactions.",
                    "children": [],
                },
            ],
        },
        {
            "name": "Concerted pericyclic reorganization",
            "kind": "principle",
            "desc": "Reactivity through a single cyclic transition state with no "
                    "intermediate, governed by conservation of orbital symmetry "
                    "(Woodward-Hoffmann rules).",
            "children": [
                {
                    "name": "Cycloaddition",
                    "kind": "mechanism", "host": True,
                    "desc": "Concerted combination of two pi-systems into a ring "
                            "(Diels-Alder and other [m+n] cycloadditions) with "
                            "suprafacial/antarafacial stereochemistry.",
                    "children": [],
                },
                {
                    "name": "Sigmatropic & electrocyclic rearrangement",
                    "kind": "mechanism", "host": True,
                    "desc": "Intramolecular concerted bond reorganization: "
                            "sigmatropic shifts and electrocyclic ring "
                            "opening/closing.",
                    "children": [],
                },
            ],
        },
        {
            "name": "Organometallic catalytic cycle",
            "kind": "principle",
            "desc": "Bonds are made and broken at a metal center through elementary "
                    "organometallic steps; the metal lowers the activation barrier "
                    "and is regenerated each turnover.",
            "children": [
                {
                    "name": "Oxidative addition / transmetalation / reductive elimination",
                    "kind": "mechanism", "host": True,
                    "desc": "The cross-coupling catalytic cycle: oxidative addition of "
                            "an organohalide to a low-valent metal, transmetalation "
                            "with an organometallic partner, then reductive "
                            "elimination forming C-C or C-heteroatom bonds "
                            "(Suzuki, Negishi, Buchwald-Hartwig, ...).",
                    "children": [],
                },
                {
                    "name": "Migratory insertion / beta-hydride elimination",
                    "kind": "mechanism", "host": True,
                    "desc": "Insertion of an alkene or CO into a metal-carbon bond "
                            "followed by beta-hydride elimination; the basis of the "
                            "Heck reaction and insertion polymerization.",
                    "children": [],
                },
                {
                    "name": "Metal-carbene metathesis",
                    "kind": "mechanism", "host": True,
                    "desc": "Alkene/alkyne fragment redistribution through a "
                            "metal-carbene and metallacyclobutane intermediate "
                            "(ring-closing, cross and ring-opening metathesis).",
                    "children": [],
                },
            ],
        },
    ],
}

# ── by_substance_class: principle -> class -> leaf(molecule/material) ────────
SUBSTANCE_TREE = {
    "name": "(unifying principle unknown)",
    "kind": "open_root",
    "desc": "No single principle defines all matter; the top level is a forest "
            "of bonding/structure principles that determine substance identity "
            "and properties.",
    "children": [
        {
            "name": "Metal-ligand coordination bonding",
            "kind": "principle",
            "desc": "Substances whose identity is set by dative metal-ligand bonds, "
                    "d-electron configuration and coordination geometry.",
            "children": [
                {
                    "name": "Transition-metal complexes",
                    "kind": "class", "host": True,
                    "desc": "Discrete transition-metal coordination and organometallic "
                            "complexes with phosphine, N-heterocyclic carbene or "
                            "related ligands (Pd, Ni, Ru, Ir, Cu, ...).",
                    "children": [],
                },
            ],
        },
        {
            "name": "Directional covalent bonding & conjugation",
            "kind": "principle",
            "desc": "Molecules whose properties derive from covalent connectivity, "
                    "pi-conjugation and aromaticity.",
            "children": [
                {
                    "name": "Aromatic & heteroaromatic molecules",
                    "kind": "class", "host": True,
                    "desc": "Benzenoid and heteroaromatic small molecules and their "
                            "substituted derivatives (arenes, pyridines, thiophenes).",
                    "children": [],
                },
            ],
        },
        {
            "name": "Macromolecular chain connectivity",
            "kind": "principle",
            "desc": "Substances built from many covalently linked repeat units "
                    "forming chains or networks.",
            "children": [
                {
                    "name": "Synthetic polymers",
                    "kind": "class", "host": True,
                    "desc": "Synthetic polymers and copolymers: polyolefins, polyesters, "
                            "conjugated polymers and block copolymers.",
                    "children": [],
                },
            ],
        },
        {
            "name": "Nanoscale confinement & surface dominance",
            "kind": "principle",
            "desc": "Materials whose behavior is governed by nanoscale dimensions and "
                    "a high surface-to-volume ratio.",
            "children": [
                {
                    "name": "Nanoparticles & nanostructures",
                    "kind": "class", "host": True,
                    "desc": "Metal and metal-oxide nanoparticles, nanostructured "
                            "catalysts, quantum dots and supported nanomaterials.",
                    "children": [],
                },
            ],
        },
    ],
}

PILOT_TREES = {
    "by_reaction_type": REACTION_TREE,
    "by_substance_class": SUBSTANCE_TREE,
}


def iter_leaf_branches(node, path=None):
    """Yield ``(path, node)`` for every leaf-hosting branch (``host=True``)."""
    path = (path or []) + [node["name"]]
    if node.get("host"):
        yield path, node
    for child in node.get("children", []):
        yield from iter_leaf_branches(child, path)


def leaf_branches(view_id):
    """Return ``[(path, name, desc), ...]`` for a view's leaf-hosting branches."""
    tree = PILOT_TREES[view_id]
    return [(path, node["name"], node["desc"])
            for path, node in iter_leaf_branches(tree)]
