-- Generated by scripts/extract_runtime_schema.py.
PRAGMA journal_mode=WAL;
PRAGMA synchronous=NORMAL;
CREATE TABLE IF NOT EXISTS api_keys (
            key_id TEXT PRIMARY KEY,
            key_hash TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            email TEXT,
            tier TEXT DEFAULT 'free',
            rate_limit INTEGER DEFAULT 100,
            created_at TEXT NOT NULL,
            last_used_at TEXT,
            is_active INTEGER DEFAULT 1,
            user_id TEXT
        , total_requests INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS bookmarks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT NOT NULL,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            title TEXT,
            note TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(user_id),
            UNIQUE(user_id, target_type, target_id)
        );
CREATE TABLE IF NOT EXISTS click_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            query_log_id INTEGER,
            query TEXT,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            position INTEGER,
            user_id TEXT,
            ip_hash TEXT
        );
CREATE TABLE IF NOT EXISTS community_flags (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            claim_id TEXT NOT NULL,
            flag_type TEXT NOT NULL,  -- wrong_claim, wrong_classification, not_chemistry, duplicate, other
            category TEXT,            -- e.g. which view/path is wrong
            comment TEXT,
            suggested_fix TEXT,
            reporter_name TEXT,
            reporter_email TEXT,
            status TEXT DEFAULT 'open',  -- open, reviewed, resolved, dismissed
            created_at TEXT NOT NULL,
            reviewed_at TEXT,
            reviewer_notes TEXT
        );
CREATE TABLE IF NOT EXISTS edge_jobs (
            paper_doi      TEXT NOT NULL,
            mode           TEXT NOT NULL,
            extractor      TEXT NOT NULL,
            status         TEXT NOT NULL,   -- 'done' | 'failed' | 'skipped'
            edges_inserted INTEGER NOT NULL DEFAULT 0,
            tokens_in      INTEGER NOT NULL DEFAULT 0,
            tokens_out     INTEGER NOT NULL DEFAULT 0,
            error          TEXT,
            started_at     TEXT NOT NULL,
            finished_at    TEXT,
            PRIMARY KEY (paper_doi, mode, extractor)
        );
CREATE TABLE IF NOT EXISTS feedback (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT NOT NULL,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            feedback_type TEXT NOT NULL,
            comment TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(user_id),
            UNIQUE(user_id, target_type, target_id, feedback_type)
        );
CREATE TABLE IF NOT EXISTS key_usage (
            key_id TEXT NOT NULL,
            date TEXT NOT NULL,
            request_count INTEGER DEFAULT 0,
            PRIMARY KEY (key_id, date)
        );
CREATE TABLE IF NOT EXISTS ltree_feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, view_id TEXT NOT NULL, node_id TEXT, doi TEXT, kind TEXT NOT NULL, comment TEXT, reporter_name TEXT, reporter_email TEXT, ip_hash TEXT, status TEXT DEFAULT 'open', created_at TEXT NOT NULL, reviewed_at TEXT, reviewer_notes TEXT);
CREATE TABLE IF NOT EXISTS notification_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            subscription_id INTEGER NOT NULL,
            sent_at TEXT NOT NULL,
            claim_count INTEGER DEFAULT 0,
            status TEXT DEFAULT 'sent',
            error TEXT,
            FOREIGN KEY (subscription_id) REFERENCES subscriptions(id)
        );
CREATE TABLE IF NOT EXISTS query_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            query TEXT NOT NULL,
            endpoint TEXT NOT NULL,
            view TEXT,
            filters TEXT,
            result_count INTEGER DEFAULT 0,
            latency_ms REAL DEFAULT 0,
            user_agent TEXT,
            ip_hash TEXT,
            user_id TEXT
        );
CREATE TABLE IF NOT EXISTS reading_list_items (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            list_id INTEGER NOT NULL,
            target_type TEXT NOT NULL,
            target_id TEXT NOT NULL,
            title TEXT,
            note TEXT,
            position INTEGER DEFAULT 0,
            added_at TEXT NOT NULL,
            FOREIGN KEY (list_id) REFERENCES reading_lists(id),
            UNIQUE(list_id, target_type, target_id)
        );
CREATE TABLE IF NOT EXISTS reading_lists (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT NOT NULL,
            name TEXT NOT NULL,
            description TEXT,
            is_public INTEGER DEFAULT 0,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(user_id)
        );
CREATE TABLE IF NOT EXISTS saved_searches (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id TEXT NOT NULL,
            name TEXT,
            query TEXT NOT NULL,
            view TEXT,
            filters TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(user_id)
        );
CREATE TABLE IF NOT EXISTS security_log (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            timestamp TEXT NOT NULL,
            event_type TEXT NOT NULL,
            ip_hash TEXT,
            details TEXT
        );
CREATE TABLE IF NOT EXISTS submissions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            doi TEXT NOT NULL,
            submitted_at TEXT NOT NULL,
            status TEXT DEFAULT 'pending',  -- pending, processing, completed, failed
            submitter_name TEXT,
            submitter_email TEXT,
            notes TEXT,
            result TEXT  -- JSON with extraction/classification results
        );
CREATE TABLE IF NOT EXISTS subscriptions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT,
            sub_type TEXT NOT NULL,
            target TEXT NOT NULL,
            frequency TEXT DEFAULT 'weekly',
            created_at TEXT NOT NULL,
            is_active INTEGER DEFAULT 1,
            last_notified_at TEXT,
            user_id TEXT
        , manage_token TEXT);
CREATE TABLE IF NOT EXISTS user_sessions (
            session_token TEXT PRIMARY KEY,
            user_id TEXT NOT NULL,
            created_at TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            FOREIGN KEY (user_id) REFERENCES users(user_id)
        );
CREATE TABLE IF NOT EXISTS users (
            user_id TEXT PRIMARY KEY,
            email TEXT NOT NULL,
            display_name TEXT,
            clerk_id TEXT,
            created_at TEXT NOT NULL,
            last_login_at TEXT
        );
CREATE INDEX IF NOT EXISTS idx_apikeys_hash ON api_keys(key_hash);
CREATE INDEX IF NOT EXISTS idx_apikeys_user ON api_keys(user_id, is_active);
CREATE INDEX IF NOT EXISTS idx_bookmarks_target ON bookmarks(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_bookmarks_user ON bookmarks(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_clicklog_qlid ON click_log(query_log_id);
CREATE INDEX IF NOT EXISTS idx_clicklog_ts ON click_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_clicklog_user ON click_log(user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_edge_jobs_mode_status
            ON edge_jobs(mode, extractor, status);
CREATE INDEX IF NOT EXISTS idx_feedback_target
            ON feedback(target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_feedback_user ON feedback(user_id);
CREATE INDEX IF NOT EXISTS idx_flags_claim ON community_flags(claim_id);
CREATE INDEX IF NOT EXISTS idx_flags_status ON community_flags(status);
CREATE INDEX IF NOT EXISTS idx_flags_type ON community_flags(flag_type);
CREATE INDEX IF NOT EXISTS idx_key_usage_date ON key_usage(date);
CREATE INDEX IF NOT EXISTS idx_ltfb_node ON ltree_feedback(view_id, node_id);
CREATE INDEX IF NOT EXISTS idx_ltfb_status ON ltree_feedback(status);
CREATE INDEX IF NOT EXISTS idx_notif_sub ON notification_log(subscription_id);
CREATE INDEX IF NOT EXISTS idx_querylog_query ON query_log(query);
CREATE INDEX IF NOT EXISTS idx_querylog_ts ON query_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_querylog_user ON query_log(user_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_reading_lists_public
            ON reading_lists(is_public, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_reading_lists_user
            ON reading_lists(user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_rlist_items_list
            ON reading_list_items(list_id, position, added_at);
CREATE INDEX IF NOT EXISTS idx_saved_searches_user
            ON saved_searches(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_log_ts ON security_log(timestamp);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON user_sessions(expires_at);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON user_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions(status);
CREATE INDEX IF NOT EXISTS idx_subs_active ON subscriptions(is_active);
CREATE INDEX IF NOT EXISTS idx_subs_email ON subscriptions(email);
CREATE INDEX IF NOT EXISTS idx_subs_user ON subscriptions(user_id, is_active);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_clerk ON users(clerk_id) WHERE clerk_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
