#!/usr/bin/env python3
"""Extract the allowlisted private/runtime SQLite schema from a service DB."""

from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

RUNTIME_TABLES = (
    "submissions",
    "query_log",
    "click_log",
    "api_keys",
    "subscriptions",
    "notification_log",
    "community_flags",
    "ltree_feedback",
    "key_usage",
    "security_log",
    "edge_jobs",
    "users",
    "user_sessions",
    "feedback",
    "bookmarks",
    "saved_searches",
    "reading_lists",
    "reading_list_items",
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--db", type=Path, default=ROOT / "askchem.db")
    parser.add_argument(
        "--output", type=Path, default=ROOT / "src/askchem/runtime_schema.sql",
    )
    args = parser.parse_args()

    conn = sqlite3.connect(f"file:{args.db}?mode=ro", uri=True)
    placeholders = ",".join("?" for _ in RUNTIME_TABLES)
    rows = conn.execute(
        "SELECT type, name, sql FROM sqlite_master "
        f"WHERE tbl_name IN ({placeholders}) "
        "AND type IN ('table','index') AND sql IS NOT NULL "
        "ORDER BY CASE type WHEN 'table' THEN 0 ELSE 1 END, name",
        RUNTIME_TABLES,
    ).fetchall()
    conn.close()
    sql = [
        "-- Generated by scripts/extract_runtime_schema.py.\n",
        "PRAGMA journal_mode=WAL;\n",
        "PRAGMA synchronous=NORMAL;\n",
    ]
    sql.extend(statement.rstrip(";") + ";\n" for _, _, statement in rows)
    args.output.write_text("".join(sql))
    print(f"wrote {len(rows)} schema objects to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
